name: 'weather_analytics'
version: '1.0.0'
config-version: 2

profile: 'weather_profile'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  weather_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table